version: '3.8'

services:
  eureka-server:
    build: ./registry
    ports:
      - "8761:8761"
    networks:
      - micro-net

  producer-service:
    build: ./producer_resource
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - micro-net

  consumer-service:
    build: ./consumer_resource
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - micro-net

  front-end:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - eureka-server
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: inventorydb
    networks:
      - micro-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: inventorydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
networks:
  micro-net:
    driver: bridge

volumes:
  pgdata:
